### ISSUE TITLE
Crashing Insurgency Server

### ISSUE THREAD

**Issue by andydigi** [alliedmodders/sourcemod#664] opened 2017-08-20 14:45 UTC
Since Insurgency was updated the other day I cannot run Sourcemod 1.8.0 even with git6024.
The server log shows this:-
For FCVAR_REPLICATED, ConVar must be defined in client and game .dlls (sv_radial_spam_delay_leaderfrac)
Parent cvar in server.dll not allowed (ins_bot_arousal_suppression_falloff)
Unable to restore Weapon_p2a1.Empty from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_p2a1.OpenBarrel from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_p2a1.RemoveEmptyFlare from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_p2a1.FlareInStart from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_p2a1.FlareIn from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_p2a1.FlareDrop from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_p2a1.CloseBarrel from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_p2a1.CockHammer from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_M67.ArmDraw from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_C4.InsurgentDetonator from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.
Unable to restore Weapon_IED.Throw from the soundcache, no sound index! Ensure game_sounds_manifest.txt includes the script containing this.

**Comment by psychonic** [comment] 2017-08-26 14:38
Duplicate of #646

**Closed by psychonic** 2017-08-26 14:38 UTC
