### ISSUE TITLE
1.11 Files being marked as malicious. 1.10 Not working on x64 bit server.

### ISSUE THREAD

**Issue by goblineer-gaming** [alliedmodders/sourcemod#2185] opened 2024-06-20 11:41 UTC
Hi, I host a TF2 server that obviously is using sourcemod for basic utility commands, and some fun ones. I host it on Streamline Servers that has an in-built mod manager for downloading and updating some plugins. I downloaded the 1.11 stable build, I extracted it somewhere to upload it, and my antivirus flagged some files and removed them from my computer. In the sites mod manager, it also flagged files as malicious and prevent the install. Also, I switched the executable used for the server to the x64 build, then 1.10 decided to cease function. Either that's due to 1.10 (probably) not being compatible with TF2 x64 build, or it's a small bug with it.

**Comment by caxanga334** [comment] 2024-06-20 11:43
> my antivirus flagged some files and removed them from my computer

False positive, report to your AV vendor and whitelist the server addons folder as a workaround for now.

> I switched the executable used for the server to the x64 build, then 1.10 decided to cease function. Either that's due to 1.10 (probably) not being compatible with TF2 x64 build

1.10 is old and is no longer supported. For x64 TF2 you need Metamod Source 2.0 and Sourcemod 1.12.

**Comment by nosoop** [comment] 2024-06-20 11:44
Duplicate of #2144.

An alternative stopgap solution is to use build [6963](https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6963-windows.zip) with a 32-bit server instance.

**Closed** 2024-06-20 14:30 UTC
