### ISSUE TITLE
Methodmap definitions do not look ahead for method signatures

### ISSUE THREAD

**Issue by geominorai** [alliedmodders/sourcemod#1452] opened 2021-03-22 01:38 UTC
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Current SourceMod version: 1.10.0.6502

# Description
Methods appear to be parsed sequentially in Methodmap declarations.  Unlike normal functions, this makes it impossible to call functions defined below it or even the same function itself recursively.

# Problematic Code
  ```cpp
methodmap Test {
	public void FuncA() {
		this.FuncB(); // error 105: cannot find method or property Test.FuncB
	}

	public void FuncB() {

	}
}
  ```
```cpp
methodmap Test {
	public void Recursion(int i) {
		if (i > 0) {
			this.Recursion(i-1); // error 105: cannot find method or property Test.Recursion
		}
	}
}
```

**Comment by peace-maker** [comment] 2021-03-22 10:42
This is a duplicate of https://github.com/alliedmodders/sourcepawn/issues/230.

**Closed by peace-maker** 2021-03-22 10:42 UTC

**Comment by geominorai** [comment] 2021-03-22 10:51
> This is a duplicate of https://github.com/alliedmodders/sourcepawn/issues/230.

That issue only mentions recursion case but i hope the.

**Comment by peace-maker** [comment] 2021-03-22 10:52
> That issue only mentions recursion case but I hope the other is not forgotten.

Oh, you're right, sorry. Feel free to add that aspect to the linked issue!
