### ISSUE TITLE
Heap/stack corruption on map change following bot spawning

### ISSUE THREAD

**Issue by geominorai** [alliedmodders/sourcemod#748] opened 2018-01-14 16:56 UTC
Linux TF2 server segfaults on map change after spawning a puppet bot

TF2 srcds v4294355 
Sourcemod v1.8.0.6040
Metamod 1.10.7-git961

Reproduction steps:
1. Start/restart server normally with a startup map (no need for players to even join the server)
2. Enter in server console:  `sv_cheats 1; bot -name SomeBOT -class soldier; sv_cheats 0`
3. Enter in server console: `changelevel (some other map)`
4. Crashes showing in console log: corrupted size vs. prev_size

Repeatability:
- Almost always (> 70% of the time via reproduction steps on my server)
- Crash does not happen without spawning the bot
- Crash does not happen without Sourcemod loaded
- Crash does not happen with only Metamod loaded

Time frame:
- Noticed this on a plugin of mine that spawns bots after the Jungle update.  Debugged for weeks to find out the same crash can happen without running any plugins at all.

Crash dump: https://crash.limetech.org/a4w7wssvn6z6
Additional log file: [debug.log](https://github.com/alliedmodders/sourcemod/files/1629530/debug.log)

Plugins loaded:
- [None]  (tested with empty plugins folder)

Extensions loaded:
- bintools.ext.so
- game.tf2.ext.2.tf2.so
- sdkhooks.ext.2.tf2.so
- sdktools.ext.2.tf2.so
- updater.ext.so
- webternet.ext.so

**Comment by Fyren** [comment] 2018-01-14 17:58
I can reproduce this on my Linux server.  Beyond what was already said, the crash occurs on the latest 1.9 build and without any SM extensions loaded.  Choice of map seems to matter in some way.  I started the server on itemtest and running `sv_cheats 1; bot -name SomeBOT -class soldier; sv_cheats 0; wait 60; changelevel pl_goldrush` would always crash for me.

**Comment by geominorai** [comment] 2018-01-19 05:38
If I manually kick the bot prior to switching the map, the crash does not seem to happen.  However, it is too late by the time `OnMapEnd` is called because bots are automatically removed by the server at that point and the crash will happen at the start of the next map.

This also means I cannot predict when a map will end beforehand to use this workaround, and any plugin that calls SM's `ForceChangeLevel` function will crash the server on top of the normal map cycling.

**Comment by xNanochip** [comment] 2018-03-07 04:06
Getting this issue with tf bots as well.

**Comment by Glubbable** [comment] 2018-04-02 18:12
I can confirm that I am having this crash issue with regular bots as well. However, important thing to note for me is that this crash does not occure on a server running under Debian, but does occure if the server is running Ubuntu.

**Comment by Benoist3012** [comment] 2018-04-02 19:56
Made a crash "avoider", https://forums.alliedmods.net/showthread.php?p=2585800
Won't fix the issue, but at least it should help people suffering from this. I would have loved to help fixing that issue but I've no idea where to look or start or what may even be the root issue, so I hope someone with will give us a proper fix.

**Comment by geominorai** [comment] 2018-04-02 20:47
@Glubbable: Can confirm; it crashes on Ubuntu but also on Gentoo, which is what NFOservers Linux machines also run.

**Comment by KyleSanderson** [comment] 2018-05-21 05:03
Does this still happen after todays fix?

**Comment by Fyren** [comment] 2018-05-21 11:41
There's practically zero change this is related to the convar change.  That only started after our change in early May.

**Comment by sigsegv-mvm** [comment] 2019-10-31 18:49
To everyone following this thread: I highly recommend that you take a look at #1007 (and the fix in #1008). I'm pretty sure that I found the root cause of this problem, once and for all. Plus a fix for it.

Try a SourceMod rebuild with the latest commits and see if your heap corruption problems go away!

**Comment by sigsegv-mvm** [comment] 2019-10-31 23:08
Oh... and oops, in my previous post I referenced the wrong issue/PR numbers. :roll_eyes:

Fixed now.

**Comment by asherkin** [comment] 2021-07-18 22:29
Gonna go ahead and hope this was fixed by the PlayerManager changes 🤞

**Closed by asherkin** 2021-07-18 22:29 UTC
Labels: Bug
