### ISSUE TITLE
 SDKHooks_DropWeapon crashes server 

### ISSUE THREAD

**Issue by Alexeyt89** [alliedmodders/sourcemod#1680] opened 2021-12-27 10:14 UTC
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Linux
  * Game/AppID (with version if applicable):  730
  * Current SourceMod version:  1.11.0.6826
  * Current SourceMod snapshot:  1.11.0.6826
  * Current Metamod: Source snapshot: 1.12.0-dev+1157

# Description
In order to disable hook bypassing of weapon drops, 5-th argument of SDKHooks_DropWeapon should be set to false. In current version bypassing can only be disabled if valid origin and velocity vectors are provided (NULL_VECTOR is not supported yet):

                float origin[3];
                origin[0] = 0.0;
                origin[1] = 0.0;
                origin[2] = 0.0;

                float velocity[3];
                velocity[0] = 0.0;
                velocity[1] = 0.0;
                velocity[2] = 0.0;

                SDKHooks_DropWeapon(client, weapon, origin, velocity, false);

But if valid vectors are set, the call crashes the server.

# Logs
[8b74d282-c3bd-4910-8ebe4f8d-a37e0c04.dmp.zip](https://github.com/alliedmodders/sourcemod/files/7779682/8b74d282-c3bd-4910-8ebe4f8d-a37e0c04.dmp.zip)

**Comment by asherkin** [comment] 2021-12-27 10:52
This appears to be a duplicate of #1670, which was fixed in build 6841.

**Closed** 2021-12-28 13:18 UTC
