### ISSUE TITLE
Run commands on target with sm_play

### ISSUE THREAD

**Issue by Rushaway** [alliedmodders/sourcemod#1950] opened 2023-03-12 14:03 UTC
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Ubuntu 20.04
  * Game/AppID (with version if applicable): CS:S/CS:GO/ANY?
  * Current SourceMod version: 1.11.0.6931
  * Current SourceMod snapshot: 1.12.0.6982
  * Current Metamod: Source snapshot: 1.12.0-dev+1167
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Related to #1832 
For example, if I had basic `sm_play `access as a moderator, and there were no immunity checks on targetting higher admins, I would be able to run `!play <target> "\";sm_ban boink 0 reason"`, and the plugin would be running both `playgamesound `and `sm_ban `as two individual commands through `ClientCommand("")`, on the targetted player.

# Problematic Code (or Steps to Reproduce)
  ```
 !play Dolly "";sm_slay Rushaway"
  ```
  The empty "" is to do not specify any files to play

# Logs
```
de_dust2 (CT: 0 | T: 0) - 01/15/2023 @ 12:13:02 
.Rushaway<62><[U:1:44340774]><> played sound on Dolly<69><[U:1:1060928058]><> (file \)
de_dust2 (CT: 0 | T: 0) - 01/15/2023 @ 12:13:02 
.Rushaway<62><[U:1:44340774]><> slayed .Rushaway<62><[U:1:44340774]><>
```

**Comment by KyleSanderson** [comment] 2023-03-14 19:24
duplicate of the issue in the OP.

**Closed by KyleSanderson** 2023-03-14 19:24 UTC
