### ISSUE TITLE
OnDBConnect - Could not find database config after moving 6267 -> 6331

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#882] opened 2018-09-11 07:18 UTC
# Help us help you
  - [v] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux server
  * Game/AppID (with version if applicable): Left4dead 1
  * Current SourceMod version: 1.10.6331
  * Current Metamod: Source snapshot: 1.11
  - [v] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [v] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
After updating server from 1.10.0.6267 to 1.10.0.6331, I'm receiving such error:
```
L 09/11/2018 - 10:09:00: [vip/VIP_Core.smx] OnLibraryAdded: vip_core
L 09/11/2018 - 10:09:00: [SM] Exception reported: OnDBConnect Could not find database config "vip"
L 09/11/2018 - 10:09:00: [SM] Blaming: vip/VIP_Core.smx
L 09/11/2018 - 10:09:00: [SM] Call stack trace:
L 09/11/2018 - 10:09:00: [SM]   [0] SetFailState
L 09/11/2018 - 10:09:00: [SM]   [1] Line 41, vip/db.sp::OnDBConnect
```
I checked it twice. After reverting bin, extensions and plugins files back to 1.10.0.6267, connection is OK.

# Problematic Code (or Steps to Reproduce)
I dunno, just ask what you need.
Here is a plugin. No sources. [-REMOVED-](https://google.com/)

**Comment by dragokas** [comment] 2018-09-11 15:59
> You must give the source if you are going to distribute the plugin binary. I removed your link
I'm not going to distribute. It was for your conveniences. But if you don't need it, you are the boss.

> edit: can you show what your database.cfg looks like? Please ensure you blank out sensitive information
Please, 
[databases.zip](https://github.com/alliedmodders/sourcemod/files/2371742/databases.zip)

**Comment by Headline** [comment] 2018-09-11 18:01
@dragokas in the config you uploaded it doesn't appear that `vip` has an entry in the databases.cfg, which is what the error indicates. Adding the configuration into the file should resolve this problem

**Comment by asherkin** [comment] 2018-09-11 18:33
Please post at least the entire `vip/db.sp::OnDBConnect` function.

**Comment by asherkin** [comment] 2018-09-11 18:40
This is a duplicate of #865.

**Closed by asherkin** 2018-09-11 18:40 UTC

**Comment by dragokas** [comment] 2018-09-11 19:13
Headline, I also see that there are no "vip" cfg.
But I see what I see, with previous build it work ok (database.cfg file is untoched and was the same for both cases).

**Comment by Headline** [comment] 2018-09-11 19:14
asherkin and I have confirmed that this is a duplicate of #865, and *is* still a sourcemod bug. It will be fixed in the coming week(s)

**Comment by dragokas** [comment] 2018-09-11 19:44
asherkin:

`DB_Connect()
{
	if (g_iClientInfo[0] & 4)
	{
		return 0;
	}
	if (g_hDatabase)
	{
		new var1 = g_iClientInfo;
		var1[0] = var1[0] & -5;
		return 0;
	}
	new var2 = g_iClientInfo;
	var2[0] = var2[0] | 4;
	if (SQL_CheckConfig("vip"))
	{
		SQL_TConnect(OnDBConnect, "vip", any:1);
	}
	else
	{
		decl String:sError[256];
		sError[0] = MissingTAG:0;
		g_hDatabase = SQLite_UseDatabase("vip", sError, 256);
		OnDBConnect(g_hDatabase, g_hDatabase, sError, any:0);
	}
	return 0;
}

public OnDBConnect(Handle:hOwner, Handle:hQuery, String:sError[], any:data)
{
	new var1;
	if (hQuery && sError[0])
	{
		SetFailState("OnDBConnect %s", sError);
		new var2 = g_iClientInfo;
		var2[0] = var2[0] & -5;
		return 0;
	}
	...`

**Comment by CrazyHackGUT** [comment] 2018-09-13 02:58
You decompiled? Seriously?

https://github.com/R1KO/VIP-Core/blob/11bb1fec61e0d9ab2ab388c5011d1de7e5000d35/addons/sourcemod/scripting/vip/Database.sp#L6-L70
