### ISSUE TITLE
Build 6016 - Insurgency SRCDS Segfault

### ISSUE THREAD

**Issue by GiZZoR** [alliedmodders/sourcemod#646] opened 2017-08-03 14:35 UTC
Build 6016 is causing segfault when on vanilla install of Insurgency dedicated server on Linux (not sure about Windows). 
Roll back to 6015 resolves issue.

No useful error message provided to console or debug.log.

**Comment by psychonic** [comment] 2017-08-03 14:38
This is a known issue for now. We use the same build for Insurgency and Day of Infamy since they share the same engine code. However, Insurgency hasn't had a game update since DOI's last breaking change. When it does, it will be compatible with the newer SM builds.

**Comment by psychonic** [comment] 2017-08-15 17:07
Today's Insurgency update should cause these later Metamod:Source and SourceMod builds to function again (and now be required).

**Comment by GiZZoR** [comment] 2017-08-23 14:17
This is not resolved.
Just tested with latest srcds and sourcemod versions, issue persists. Rolled back to 6015.

**Comment by asherkin** [comment] 2017-08-23 14:19
@GiZZoR this is tracked in #664.

**Comment by psychonic** [comment] 2017-08-23 14:29
#664 is probably a duplicate of this.

I haven't had time yet to see if this is the same issue after the game update or if it's a different breaking change. If it's the same change, it's also unclear whether they rolled back their appsystem change or if they're now using a branch model where Insurgency and DoI don't necessarily build on the same engine anymore.

**Comment by psychonic** [comment] 2017-08-26 14:39
I can confirm that this is the same IAppSystem change. I'm not entirely sure why it's crashing in a different place, but it's definitely the same issue. I'm now leaning toward us splitting DoI off to its own SDK.

**Comment by KyleSanderson** [comment] 2017-09-24 14:54
@Gizzor is this still an issue?

**Comment by ambaca** [comment] 2017-09-30 18:23
Hi. Seems this bug have been already reported.
And it still exist, at least OS Windows version, I just tested. Build 6015 still work.

**Comment by GiZZoR** [comment] 2017-10-23 19:27
@KyleSanderson I can confirm that this is still an issue. Tested on vanilla install with latest MM & SM stable builds.

**Comment by rsgua** [comment] 2017-10-31 02:02
When fix sourcemod?

**Comment by psychonic** [comment] 2017-11-04 13:06
The latest stable and dev builds of MM:S and SM now work on both Insurgency and Day of Infamy.

**Closed by psychonic** 2017-11-04 13:06 UTC
