### ISSUE TITLE
servercrash , please help

### ISSUE THREAD

**Issue by haskellstudio** [alliedmodders/sourcemod#774] opened 2018-02-27 09:34 UTC
the crash function address is 0008EE80 in sourcemod.2.csgo.so
the problem is when exec   `movzx   eax, byte ptr [edi]` , the code didn't check the edi is a valid address after the code `.text:0008EE6A                 call    dword ptr [eax+8]`
please help me to locate the source , i can not find function `FireEvent0::Func `in sourcemod repositry. thank you!

```
.text:0008ECD0 ; __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *, bool)
.text:0008ECD0 _ZN47__SourceHook_FHCls_IGameEventManager2FireEvent04FuncEP10IGameEventb proc near
.text:0008ECD0                                         ; DATA XREF: .rodata:off_1CD4E8o
.text:0008ECD0                 push    ebp
.text:0008ECD1                 push    ebx
.text:0008ECD2                 push    edi
.text:0008ECD3                 push    esi
.text:0008ECD4                 sub     esp, 3Ch
.text:0008ECD7                 mov     edi, [esp+54h]
.text:0008ECDB                 mov     ebx, [esp+50h]
.text:0008ECDF                 mov     eax, ds:dword_23C884
.text:0008ECE4                 mov     ecx, ds:dword_23C880
.text:0008ECEA                 shl     ecx, 2
.text:0008ECED                 add     ecx, [ebx+eax]
.text:0008ECF0                 mov     dword ptr [esp+34h], 0
.text:0008ECF8                 mov     eax, ds:g_SHPtr
.text:0008ECFD                 mov     edx, [eax]
.text:0008ECFF                 mov     esi, ds:_ZN47__SourceHook_FHCls_IGameEventManager2FireEvent05ms_HIE ; __SourceHook_FHCls_IGameEventManager2FireEvent0::ms_HI
.text:0008ED05                 lea     ebp, [esp+2Ah]
.text:0008ED09                 mov     [esp+24h], ebp
.text:0008ED0D                 lea     ebp, [esp+2Bh]
.text:0008ED11                 mov     [esp+20h], ebp
.text:0008ED15                 lea     ebp, [esp+2Ch]
.text:0008ED19                 mov     [esp+1Ch], ebp
.text:0008ED1D                 lea     ebp, [esp+30h]
.text:0008ED21                 mov     [esp+18h], ebp
.text:0008ED25                 lea     ebp, [esp+34h]
.text:0008ED29                 mov     [esp+14h], ebp
.text:0008ED2D                 lea     ebp, [esp+38h]
.text:0008ED31                 mov     [esp+10h], ebp
.text:0008ED35                 mov     [esp+0Ch], ebx
.text:0008ED39                 mov     bh, [esp+58h]
.text:0008ED3D                 mov     [esp+8], ecx
.text:0008ED41                 mov     [esp+4], esi
.text:0008ED45                 mov     [esp], eax
.text:0008ED48                 call    dword ptr [edx+4Ch]
.text:0008ED4B                 mov     esi, eax
.text:0008ED4D                 mov     dword ptr [esp+30h], 0
.text:0008ED55                 mov     eax, [esi]
.text:0008ED57                 mov     [esp], esi
.text:0008ED5A                 call    dword ptr [eax]
.text:0008ED5C                 test    eax, eax
.text:0008ED5E                 jz      short loc_8EDB6
.text:0008ED60                 movzx   ebp, bh
.text:0008ED63                 db      66h, 66h, 66h, 66h
.text:0008ED63                 nop     word ptr cs:[eax+eax+00000000h]
.text:0008ED70
.text:0008ED70 loc_8ED70:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+E4j
.text:0008ED70                 mov     dword ptr [esp+2Ch], 0
.text:0008ED78                 mov     ecx, [eax]
.text:0008ED7A                 mov     [esp+8], ebp
.text:0008ED7E                 mov     [esp+4], edi
.text:0008ED82                 mov     [esp], eax
.text:0008ED85                 call    dword ptr [ecx+8]
.text:0008ED88                 mov     bl, al
.text:0008ED8A                 mov     eax, [esp+2Ch]
.text:0008ED8E                 mov     [esp+30h], eax
.text:0008ED92                 cmp     eax, [esp+34h]
.text:0008ED96                 jle     short loc_8ED9C
.text:0008ED98                 mov     [esp+34h], eax
.text:0008ED9C
.text:0008ED9C loc_8ED9C:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+C6j
.text:0008ED9C                 cmp     eax, 2
.text:0008ED9F                 jl      short loc_8EDAB
.text:0008EDA1                 mov     eax, [esi]
.text:0008EDA3                 mov     [esp], esi
.text:0008EDA6                 call    dword ptr [eax+4]
.text:0008EDA9                 mov     [eax], bl
.text:0008EDAB
.text:0008EDAB loc_8EDAB:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+CFj
.text:0008EDAB                 mov     eax, [esi]
.text:0008EDAD                 mov     [esp], esi
.text:0008EDB0                 call    dword ptr [eax]
.text:0008EDB2                 test    eax, eax
.text:0008EDB4                 jnz     short loc_8ED70
.text:0008EDB6
.text:0008EDB6 loc_8EDB6:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+8Ej
.text:0008EDB6                 cmp     dword ptr [esp+34h], 3
.text:0008EDBB                 jz      short loc_8EDEE
.text:0008EDBD                 mov     eax, [esi]
.text:0008EDBF                 mov     [esp], esi
.text:0008EDC2                 call    dword ptr [eax+0Ch]
.text:0008EDC5                 test    al, al
.text:0008EDC7                 jz      short loc_8EDEE
.text:0008EDC9                 mov     ecx, [esp+38h]
.text:0008EDCD                 mov     edx, [esp+50h]
.text:0008EDD1                 test    cl, 1
.text:0008EDD4                 jz      short loc_8EDDC
.text:0008EDD6                 mov     eax, [edx]
.text:0008EDD8                 mov     ecx, [ecx+eax-1]
.text:0008EDDC
.text:0008EDDC loc_8EDDC:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+104j
.text:0008EDDC                 movzx   eax, bh
.text:0008EDDF                 mov     [esp+8], eax
.text:0008EDE3                 mov     [esp+4], edi
.text:0008EDE7                 mov     [esp], edx
.text:0008EDEA                 call    ecx
.text:0008EDEC                 jmp     short loc_8EDF2
.text:0008EDEE ; ---------------------------------------------------------------------------
.text:0008EDEE
.text:0008EDEE loc_8EDEE:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+EBj
.text:0008EDEE                                         ; __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+F7j
.text:0008EDEE                 mov     al, [esp+2Ah]
.text:0008EDF2
.text:0008EDF2 loc_8EDF2:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+11Cj
.text:0008EDF2                 mov     [esp+2Bh], al
.text:0008EDF6                 mov     dword ptr [esp+30h], 0
.text:0008EDFE                 mov     eax, [esi]
.text:0008EE00                 mov     [esp], esi
.text:0008EE03                 call    dword ptr [eax]
.text:0008EE05                 test    eax, eax
.text:0008EE07                 jz      short loc_8EE56
.text:0008EE09                 movzx   ebp, bh
.text:0008EE0C                 nop     dword ptr [eax+00h]
.text:0008EE10
.text:0008EE10 loc_8EE10:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+184j
.text:0008EE10                 mov     dword ptr [esp+2Ch], 0
.text:0008EE18                 mov     ecx, [eax]
.text:0008EE1A                 mov     [esp+8], ebp
.text:0008EE1E                 mov     [esp+4], edi
.text:0008EE22                 mov     [esp], eax
.text:0008EE25                 call    dword ptr [ecx+8]
.text:0008EE28                 mov     bl, al
.text:0008EE2A                 mov     eax, [esp+2Ch]
.text:0008EE2E                 mov     [esp+30h], eax
.text:0008EE32                 cmp     eax, [esp+34h]
.text:0008EE36                 jle     short loc_8EE3C
.text:0008EE38                 mov     [esp+34h], eax
.text:0008EE3C
.text:0008EE3C loc_8EE3C:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+166j
.text:0008EE3C                 cmp     eax, 2
.text:0008EE3F                 jl      short loc_8EE4B
.text:0008EE41                 mov     eax, [esi]
.text:0008EE43                 mov     [esp], esi
.text:0008EE46                 call    dword ptr [eax+4]
.text:0008EE49                 mov     [eax], bl
.text:0008EE4B
.text:0008EE4B loc_8EE4B:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+16Fj
.text:0008EE4B                 mov     eax, [esi]
.text:0008EE4D                 mov     [esp], esi
.text:0008EE50                 call    dword ptr [eax]
.text:0008EE52                 test    eax, eax
.text:0008EE54                 jnz     short loc_8EE10
.text:0008EE56
.text:0008EE56 loc_8EE56:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+137j
.text:0008EE56                 mov     eax, [esi]
.text:0008EE58                 cmp     dword ptr [esp+34h], 2
.text:0008EE5D                 jl      short loc_8EE67
.text:0008EE5F                 mov     [esp], esi
.text:0008EE62                 call    dword ptr [eax+4]
.text:0008EE65                 jmp     short loc_8EE6D
.text:0008EE67 ; ---------------------------------------------------------------------------
.text:0008EE67
.text:0008EE67 loc_8EE67:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+18Dj
.text:0008EE67                 mov     [esp], esi
.text:0008EE6A                 call    dword ptr [eax+8]
.text:0008EE6D
.text:0008EE6D loc_8EE6D:                              ; CODE XREF: __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool)+195j
.text:0008EE6D                 mov     edi, eax
.text:0008EE6F                 mov     eax, ds:g_SHPtr
.text:0008EE74                 mov     ecx, [eax]
.text:0008EE76                 mov     [esp+4], esi
.text:0008EE7A                 mov     [esp], eax
.text:0008EE7D                 call    dword ptr [ecx+50h]
.text:0008EE80                 movzx   eax, byte ptr [edi]
.text:0008EE83                 add     esp, 3Ch
.text:0008EE86                 pop     esi
.text:0008EE87                 pop     edi
.text:0008EE88                 pop     ebx
.text:0008EE89                 pop     ebp
.text:0008EE8A                 retn
.text:0008EE8A _ZN47__SourceHook_FHCls_IGameEventManager2FireEvent04FuncEP10IGameEventb endp
```

**Comment by peace-maker** [comment] 2018-02-27 13:48
https://github.com/alliedmodders/sourcemod/blob/master/core/EventManager.cpp#L385

Do you have any other plugin/extension running that's hooking game events? You might hit https://bugs.alliedmods.net/show_bug.cgi?id=5097

**Comment by haskellstudio** [comment] 2018-02-28 07:33
yes , i have a plugin (hook player_chat event)  and an extension (hook IGameEventManager2::FireEvent)
when I remove the plugin, the server won't crash any more.  but new question come up.
I want call `SetClientName`(defined in sdktools) in my extension.  How can i call it? 

I look up the export function names in sdktools.ext.2.csgo.so by
`nm  sdktools.ext.2.csgo.so | grep ClientName`
it shows 
```
00029110 t _ZL13SetClientNamePN10SourcePawn14IPluginContextEPKi
0005f59c b _ZZL13SetClientNamePN10SourcePawn14IPluginContextEPKiE5pCall
```
How can i call it?  what's the argument type?

**Comment by peace-maker** [comment] 2018-02-28 11:36
Extensions should improve the possibilities for scripts and not replace them, so you can't call that function from sdktools. You should think about not superceding some events in your extension intead.

**Comment by psychonic** [comment] 2018-02-28 12:34
> Extensions should improve the possibilities for scripts and not replace them, so you can't call that function from sdktools.
Agreed, both with that concept, and that directly calling the internals of any first-party bin is not a supported scenario.

If you really want to change the name from the extension, your best bet is using (your own) gamedata and then using bintools to call the virtual CGameClient::SetName function after getting the IClient pointer (which there are examples of in SM code, or you can use the supposed ISDKTools::GetIServer and then IServer::GetClient)

**Comment by haskellstudio** [comment] 2018-03-09 04:15
![image](https://user-images.githubusercontent.com/27329690/37190109-e90faa94-2392-11e8-8b5e-4f54c582c41c.png)
today , the crash happens again , and the reason is same as the first post.
to: peace-maker 
the crash address is not the code 
https://github.com/alliedmodders/sourcemod/blob/master/core/EventManager.cpp#L385 
as image shows:  
there is OnFireEvent and OnFireEvent_Post .  and 
__SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent *,bool) is another function .

It's very strange that I can't find the correspond code , someone can help me ?

**Comment by haskellstudio** [comment] 2018-03-09 07:29
oh ,  i know , the fireEvent0::Func is generated by SH_ADD_HOOK , 
it is so complex ， I  can not understand what's going on...
if the crash happens again , i will restore the fireEvent hook by sourcemod .

**Comment by peace-maker** [comment] 2018-03-09 09:03
Can't help you without the code to your custom extension.

**Comment by KyleSanderson** [comment] 2018-06-18 00:48
Closing as Incomplete. This does seem to be caused by the closed source mystery extension though as indicated above.

**Closed by KyleSanderson** 2018-06-18 00:48 UTC
