### ISSUE TITLE
Syntax error in placing an inline comment

### ISSUE THREAD

**Issue by hydrogen-mvm** [alliedmodders/sourcemod#872] opened 2018-08-19 05:20 UTC
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
Spider (SourcePawn Compiler 1.9.0.5921)
Also happens on my local spcomp.

  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
spcomp raises a syntax error when placing an inline comment.
Suspected cause is the double backlash \\ is causing trouble to the parser.

# Problematic Code (or Steps to Reproduce)

This is the code that fails: (Listing A)
  ```
public void OnPluginStart()
{
	char DatabasePath[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, DatabasePath, sizeof(DatabasePath), "data/sqlite/mvm_canteen_crasher.sq3");
	ReplaceString(DatabasePath, sizeof(DatabasePath), "\\", "/");		// Normalize the slashes to prevent misery.
}
  ```

This code *works* fine: (Listing B)

  ```
public void OnPluginStart()
{
	char DatabasePath[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, DatabasePath, sizeof(DatabasePath), "data/sqlite/mvm_canteen_crasher.sq3");
	
	// Normalize the slashes to prevent misery.
	ReplaceString(DatabasePath, sizeof(DatabasePath), "\\", "/");
}
  ```

# Logs

Listing A log:
  ```
SourcePawn Compiler 1.9.0.5921
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2015 AlliedModders LLC

plugin.sp(5) : error 029: invalid expression, assumed zero
plugin.sp(5) : error 139: could not find type "the"
plugin.sp(5) : error 139: could not find type "to"
plugin.sp(5) : fatal error 190: too many error messages on one line

Compilation aborted.
4 Errors.
  ```

Listing B log:
  ```
SourcePawn Compiler 1.9.0.5921
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2015 AlliedModders LLC

Code size:             3064 bytes
Data size:             2268 bytes
Stack/heap size:      16384 bytes
Total requirements:   21716 bytes
  ```

You also may want to update the copyright year to 2018.

**Comment by Headline** [comment] 2018-08-19 06:37
@hydrogen-mvm What text encoding are you using? I'm unable to replicate this with either ANSI or UTF-8 w/o BOM

**Comment by CrazyHackGUT** [comment] 2018-08-19 08:42
Can't reproduce.
![default](https://user-images.githubusercontent.com/12576822/44307063-072f2500-a3ad-11e8-9b97-d4da04d22b56.png)

**File encoding**: UTF-8 w/o BOM.
**OS**: Windows 7 Home Premium
**Compiler**: SourcePawn 1.9 modified for internal in-game server needs

Can you attach your `A` source-code file? Maybe something wrong in charset.

**Comment by asherkin** [comment] 2018-08-19 09:33
I can reproduce on Spider, looking into it.

**Comment by asherkin** [comment] 2018-08-19 10:03
This was fixed a long time ago in alliedmodders/sourcepawn#69 (bug 6424), it is just that all the compilers you tried are outdated.

Latest 1.9 and 1.10 branch spcomp versions are fine, Spider's is from before the fix was merged, and 1.8 and older branches never got it.

**Closed by asherkin** 2018-08-19 10:03 UTC

**Comment by hydrogen-mvm** [comment] 2018-08-19 10:04
Yeah it doesn't happen on 1.10. Sorry about the issue. Thanks!

**Comment by asherkin** [comment] 2018-08-19 11:36
I've updated Spider to latest 1.9-dev spcomp and SM includes, but the caching is being aggressive so it might take a while to show up.
