### ISSUE TITLE
OnEntityCreated forward issue

### ISSUE THREAD

**Issue by Benoist3012** [alliedmodders/sourcemod#633] opened 2017-07-03 14:01 UTC
_If you don't want to read how I came around the issue please jump to "What's the problem"_

Over the last months I've been making plugins relying on this forward to make fun stuff ect...
And sometimes the intended goal didn't work as expected and I thought it was just my code being bad, said plugin ran on 5 different servers and it happened on all of them.

Recently I've been making a plugin to remove the entity `tf_ammo_pack` on the game TF2, it worked well til I noticed an ammo pack hasn't been removed I remade and remade my code again and again with different approach it always ended up to the same problem, sometimes the ammo pack wasn't removed, so I came to the conclusion OnEntityCreated must be sometimes not called at all.

# What's the problem?
It seems the forward OnEntityCreated isn't called sometimes, this issue seems very very rare.

**General infos:**
- Linux server
- Running on game Team Fortress 2

**SourceMod Version Information:**
- SourceMod Version: 1.9.0.6059
- SourcePawn Engine: 1.9.0.6059, jit-x86 (build 1.9.0.6059)
- SourcePawn API: v1 = 4, v2 = 12
- Compiled on: Mar  5 2017 14:12:07
- Built from: https://github.com/alliedmodders/sourcemod/commit/9924a28
- Build ID: 6059:9924a28
- http://www.sourcemod.net/

**Metamod:Source version 1.10.6**
- Built from: https://github.com/alliedmodders/metamod-source/commit/9fed12f
- Build ID: 946:9fed12f
- Loaded As: Valve Server Plugin
- Compiled on: Sep 12 2015
- Plugin interface version: 15:14
- SourceHook version: 5:5
- http://www.metamodsource.net/

## How reproduce the bug?
In order to reproduce the bug easily I recommend spawning a group of 32 red bots on the map `itemtest` set `nb_blind` on 1, noclip to test room, slay all the bots so they respawn in that test room, and then load the plugin I've provided with that issue, and start melee crit kill every single bot til you see one ammo box on the ground.

Screenshot of the bug occurring, I killed several bots all ammo packs got kill except one: https://steamuserimages-a.akamaihd.net/ugc/848216256556038176/657D9768A29C20226867FCCA6C7F223A98B17BCD/

**Chat debug:**

```
Entity 1178 spawned (tf_ragdoll)
Entity 1175 spawned (tf_ammo_pack)
Entity 1181 spawned (tf_ragdoll)
Entity 1222 spawned (tf_ammo_pack)
Entity 1238 spawned (tf_ragdoll)
Entity 1202 spawned (tf_ammo_pack)
Entity 1207 spawned (tf_ragdoll)
//Missing debug chat line for a newly spawned tf_ammo_pack (the one we see in the screenshot)
```

### Plugin code
```
#include <sourcemod>
#include <sdktools>
#include <sdkhooks>

#pragma newdecls required

public Plugin myinfo = 
{
	name = "[TF2] OnEntityCreated bug", 
	author = "Benoist3012", 
	description = "", 
	version = "0.1", 
	url = ""
};

public void OnEntityCreated(int iEntity, const char[] classname)
{
	//Filtering out some spammy entity
	if (strncmp(classname, "tf_weapon", 9) != 0 && strcmp(classname, "instanced_scripted_scene") != 0 && strcmp(classname, "env_sniperdot") != 0 && strcmp(classname, "tf_dropped_weapon") != 0)
		PrintToChatAll("Entity %d spawned (%s)", iEntity, classname);
	if (strcmp(classname, "tf_ammo_pack") == 0)
	{
		SDKHook(iEntity, SDKHook_SetTransmit, Hook_PackSpawn);
		SDKHook(iEntity, SDKHook_Spawn, Hook_PackSpawn);
		AcceptEntityInput(iEntity, "Kill");
	}
}

public Action Hook_PackSpawn(int iEntity)
{
	return Plugin_Handled;
}
```

#### Theory

There's maybe some kind of check that gets activated randomly that blocks the call of created entity on the game, I don't know what exactly.
I have tried to kill all bots at once see if I could get (if the theory is right) the ammo packs of all bots.
And after countless try of all bots killed at once and no single ammo pack dropped I got this:
https://steamuserimages-a.akamaihd.net/ugc/848216256556177325/10FD4705AB09338823CAA97B5B63E80EA6BA6485/
The ammo pack of all bots spawned not even one missing, even though they should have all been deleted by the plugin, and as you can see in the chat all ammo pack debug line missing.
And on this screenshot we have the normal behavior
https://steamuserimages-a.akamaihd.net/ugc/848216256556197018/A4AE6DFA6E67D083368A33086D1EE5A25FB3186F/

Ps: I did upgrade my sourcemod to latest version, and I've also downgraded it, nothing worked for me. The same issue is happening with a similar plugin I stated in my intro on 5 different servers.

**Comment by KyleSanderson** [comment] 2017-07-03 16:32
Unfortunately this sounds like a game issue.

**Comment by Benoist3012** [comment] 2017-07-03 17:06
Random question can't we make a detour on the "CreateEntityByName" function instead?

**Comment by KyleSanderson** [comment] 2017-07-03 17:58
Would that fix anything though? Are you certain the ammo being dropped actually has that classname?

**Comment by Benoist3012** [comment] 2017-07-03 18:06
Yep I'm fairly sure it is.  CTFPlayer::DropAmmoPack is called under CTFPlayer::Event_Killed, and we look at that pseudo code the classname is `tf_ammo_pack`.
```
void __usercall CTFPlayer::DropAmmoPack(long double a1@<st0>, CTFPlayer *this, const CTakeDamageInfo *a3, bool a4, bool a5)
{
//code
      v17 = CTFDroppedWeapon::Create((int)this, (Vector *)&v25, &v26, v24, v20);
      if ( v17 )
        CTFDroppedWeapon::InitDroppedWeapon(a1, v17, this, v11, 0, v21);
      v18 = CTFAmmoPack::Create((Vector *)&v25, &v26, (int)this, (int)&"models/items/ammopack_medium.mdl");
//code
}
```
```
CBaseEntity *__cdecl CTFAmmoPack::Create(Vector *s2, void *a2, int a3, int a4)
{
  CBaseEntity *v4; // ebx@1
  char v6[4]; // [sp+1Ch] [bp-Ch]@2

  v4 = CBaseEntity::CreateNoSpawn("tf_ammo_pack", s2, a2, a3);
  if ( v4 )
  {
    AllocPooledString(v6, (char *)a4);
    *((_DWORD *)v4 + 139) = *(_DWORD *)v6;
    CBaseEntity::DispatchUpdateTransmitState(v4);
    DispatchSpawn(v4);
  }
  return v4;
}
```

**Comment by psychonic** [comment] 2017-07-04 13:01
> Random question can't we make a detour on the "CreateEntityByName" function instead? (because we have already the signature for it and for every game)

Minor point, but we don't have the signature for it for most games. When calling it, we go indirectly through the IServerTools interface. The offsets we use to add and remove our listener have generally been more stable than any function signatures. I don't know if they've even ever changed upon a game update.

As you said, the CBaseEntity::CreateNoSpawn function there does call CGlobalEntityList::NotifyCreateEntity, which in turn should be calling our listener. I suspect that is actually happening, but maybe that we haven't gotten the notification of entity destruction yet for the previous entity at that index. We have a check to see if an entity already exists because the listener for NotifyCreateEntity can get called twice for an entity, depending on the path it took, but we don't want to be telling plugins twice.

It might make sense for us to store SM ent references or ehandles upon creation at the cache for an entity already existing, rather than just setting a bit. That way we can actually verify that it's a new entity taking the place or not.

@Benoist3012 would you be willing test a build with that change, to see if you can reproduce your issue?

**Comment by Benoist3012** [comment] 2017-07-04 13:11
Yes I can test a build with that change.

**Comment by InstantMuffin** [comment] 2017-07-04 18:26
If that won't fix your issue, I remember having an issue with hooks not being forwarded to plugins at random times when I was using quite an outdated version of sourcemod to compile, but my server ran an up to date build.

**Comment by psychonic** [comment] 2017-07-04 18:27
We were able to confirm that the change did fix the issue.

**Comment by InstantMuffin** [comment] 2017-07-04 18:28
Nice, thanks

**Closed** 2017-07-06 17:33 UTC
Labels: Bug
