### ISSUE TITLE
Error CreateInterface Insurgency

### ISSUE THREAD

**Issue by GoDtm666** [alliedmodders/sourcemod#734] opened 2017-12-06 06:36 UTC
Hi, install on the game Insurgency mm:s https://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git961-linux.tar.gz and sm https://sm.alliedmods.net/smdrop/1.8/sourcemod-1.8.0-git6038-linux.tar.gz when loading metamod produces an error so that it does not find the interface. (Failed to load plugin addons/sourcemod/bin/sourcemod_mm (Function CreateInterface not found))
Reassembled the package fixing in this place https://github.com/alliedmodders/metamod-source/blob/1.10-dev/core/ISmmPlugin.h#L444 #ifdef META_NO_HL2SDK overwriting to #ifndef META_NO_HL2SDK and there are no spaces with the interface, fix this problem .

**Comment by psychonic** [comment] 2017-12-06 12:24
Duplicate of #730

**Closed by psychonic** 2017-12-06 12:24 UTC
