### ISSUE TITLE
[Feature Request] Allow `GetFunctionByName` to work on public methods in enum structs and/or methodmaps

### ISSUE THREAD

**Issue by assyrianic** [alliedmodders/sourcemod#2012] opened 2023-07-02 15:37 UTC
We can make methods via C++ or SP with `TypeName.Methodname` format but `GetFunctionByName` doesn't work in that regard. I would like to request for this as a feature.

**Comment by peace-maker** [comment] 2023-07-02 16:30
Duplicate of #1932

**Closed by peace-maker** 2023-07-02 16:30 UTC
Labels: Feature Request
