### ISSUE TITLE
[x64][tf2] SDKtools AcceptEntityInput Crash

### ISSUE THREAD

**Issue by bottiger1** [alliedmodders/sourcemod#2142] opened 2024-04-27 21:54 UTC
Latest dev versions of sourcemod and metamod.

Easy repro. Does not crash on 32 bit.

```
#include <sdktools>

public OnPluginStart()
{
    RegConsoleCmd("sm_test", Cmd_Test);
}

public Action Cmd_Test(int client, int args) 
{
    int g_iop = CreateEntityByName("info_observer_point");
    DispatchKeyValue(g_iop, "Angles", "90 0 0");
    DispatchKeyValue(g_iop, "TeamNum", "0");
    DispatchKeyValue(g_iop, "StartDisabled", "0");
    DispatchSpawn(g_iop);
    //SetVariantInt(0);
    AcceptEntityInput(g_iop, "Enable");

    return Plugin_Handled;
}

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f57827264b2 in CBaseEntity::AcceptInput(char const*, CBaseEntity*, CBaseEntity*, variant_t, int) () from /home/tf2/steam/server1/tf/tf/bin/linux64/server_srv.so
[Current thread is 1 (Thread 0x7f5795692740 (LWP 4163748))]
#0  0x00007f57827264b2 in CBaseEntity::AcceptInput(char const*, CBaseEntity*, CBaseEntity*, variant_t, int) () from /home/tf2/steam/server1/tf/tf/bin/linux64/server_srv.so
#1  0x00007f577131313f in ?? ()
#2  0x000000000da99b40 in ?? ()
#3  0x000000000daeb67c in ?? ()
#4  0x00007f57714d77a0 in vec4_invalid () from /home/tf2/steam/server1/tf/tf/addons/sourcemod_idle/extensions/x64/sdktools.ext.2.tf2.so
#5  0x000000000da99b40 in ?? ()
#6  0x00007ffc93d1d140 in ?? ()
#7  0x00007f577144fe5b in AcceptEntityInput(SourcePawn::IPluginContext*, int const*) () from /home/tf2/steam/server1/tf/tf/addons/sourcemod_idle/extensions/x64/sdktools.ext.2.tf2.so

```

**Comment by Kenzzer** [comment] 2024-04-28 11:27
Potential duplicate of #2119

**Comment by bottiger1** [comment] 2024-05-04 07:17
> Potential duplicate of #2119 Please also respect issue template, and do proper post formatting

I just compiled #2119 and it still crashes.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007faca10194b2 in CBaseEntity::AcceptInput(char const*, CBaseEntity*, CBaseEntity*, variant_t, int) () from /home/tf2/steam/server1/tf/tf/bin/linux64/server_srv.so
[Current thread is 1 (Thread 0x7facabf65740 (LWP 3653751))]
#0  0x00007faca10194b2 in CBaseEntity::AcceptInput(char const*, CBaseEntity*, CBaseEntity*, variant_t, int) () from /home/tf2/steam/server1/tf/tf/bin/linux64/server_srv.so
#1  0x00007fac9a65c85f in ?? ()
#2  0x000000000be57050 in ?? ()
#3  0x0000000011ff007c in ?? ()
#4  0x00007fac9a4ce7c0 in vec4_invalid () from /home/tf2/steam/server1/tf/tf/addons/sourcemod_game/extensions/x64/sdktools.ext.2.tf2.so
#5  0x000000000be57050 in ?? ()
#6  0x00007ffc93c909c0 in ?? ()
#7  0x00007fac9a442edd in AcceptEntityInput (pContext=0x7ffc93c90997, params=0x7ffc93c90898) at /home/tf2/extensions/sdk/sourcemod/extensions/sdktools/inputnatives.cpp:101
```

**Closed** 2024-05-08 18:54 UTC
