### ISSUE TITLE
GetTickInterval() always returns 0 for CS:GO

### ISSUE THREAD

**Issue by asamy** [alliedmodders/sourcemod#607] opened 2017-05-09 21:16 UTC
Might be something to do with metamod or the hl2sdk, let me know and I will repost there instead.

Other functions related to global variables work fine, e.g. `GetGameTime()`, etc.

**Comment by psychonic** [comment] 2017-05-09 21:21
This sounds like a CS:GO quirk. Our definitions for the global vars are definitely correct, but maybe CS:GO does not populate that one.

Are you checking this mid-game, rather than when the server is hibernating?

**Comment by asamy** [comment] 2017-05-09 21:36
Yes, I am checking while the game is ongoing of course.  On the client side, writing a simple DLL that checks interval_per_tick off globals returns the correct value, though.

**Comment by psychonic** [comment] 2017-05-10 22:36
I can't reproduce this issue.

```
#include <sourcemod>

public void OnPluginStart()
{
	RegServerCmd("gti", gti);
}

public Action gti(int argc)
{
	float gti = GetTickInterval();
	PrintToServer("Tick interval is %.4f", gti);
	
	return Plugin_Handled;
}
```

With the code above, on CS:GO, the gti server command prints the same output, whether or not the server is hibernating.
`Tick interval is 0.0156`

**Comment by asherkin** [comment] 2017-05-10 22:58
I can't reproduce this either, closing.

**Closed by asherkin** 2017-05-10 22:58 UTC
Labels: Works For Me

**Comment by asamy** [comment] 2017-05-11 00:38
Maybe it's because I am calling it from OnPlayerRunCmd, the server does magic with globals in that context, so that might be it.
